### Python Libraries for data science
* Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing,processing and analysing the data
* There are nearly 20 python liraries for data science.Top five python libraries are
* TensorFlow
* Numpy
* SciPy
* Pandas
* Matplotlib
* In those libraries,Numpy and Pandas are the first choice to the data scientists who are aware of the technologies

###  NumPy:(Numerical Python)
* Numpy is Base N-Dimensional Array Package, is a python library and a fundamental package for scientific computing in Python.It is used to create multidimensional arrays for fast operations.Use the following import conversion
* import numpy as np

### Intoduction to NumPy
* The learning objectives of this section are:
* Understand advantages of vectorised code using NumPy (over standardpython ways)
* Create NumPy arrays
* Convert lists and tuples to NumPy arrays
* Create(initalise) arrays
* Inspect the structure and content of arrays
* Subset,slice,index and iterate through arrays
* Compare computation times in NumPy and standard Python lists

* There are 3 arrays 1d,2d,3d arrays

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
ar2=np.array([[1,2,3],[4,5,6]])
print(ar2)
print(type(ar2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
ar3=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
l=np.array([1,2,3,4])
l**2

array([ 1,  4,  9, 16], dtype=int32)

In [6]:
s=np.array([4,5,6,7])
l+s

array([ 5,  7,  9, 11])

In [7]:
l[1]

2

In [8]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a1=np.arange(1,10,3)
a1

array([1, 4, 7])

In [11]:
a2=np.linspace(1,2,10)
a2

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [12]:
ran(1,.5,10.5)

NameError: name 'ran' is not defined

In [13]:
a1=np.arange(1.5,10.5,2)
a2

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [14]:
ar2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
ar2.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [16]:
ar2.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
ar3.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
ar3.reshape(2,1)

ValueError: cannot reshape array of size 9 into shape (2,1)

In [19]:
a.itemsize

4

In [20]:
a.ndim

1

In [21]:
a.shape

(10,)

In [22]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [23]:
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [24]:
d=np.arange(1,500,10)
d

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121,
       131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251,
       261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381,
       391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491])

In [25]:
d[49]   #0-49

491

In [26]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
np.ones((1,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [29]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
np.eye(10,10)      #diagonal

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a2.T

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [33]:
np.transpose(ar2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
np.random.random((2,10))

array([[0.25176539, 0.72142845, 0.44773666, 0.29302205, 0.81569218,
        0.38630103, 0.95834746, 0.68421565, 0.62446509, 0.07165023],
       [0.02732175, 0.35704808, 0.76628689, 0.90970663, 0.74623284,
        0.44191946, 0.46665717, 0.99180459, 0.64625597, 0.93791199]])

In [35]:
f=np.random.randint(1,200,(25,6))
f

array([[ 26,  46, 120, 183,  43, 172],
       [ 77,  18,  61, 144, 159, 142],
       [ 97, 169,   9, 147,  80,   9],
       [ 34,  83, 142, 114,  13, 192],
       [190, 192, 182,  12,  75,  92],
       [189,  84,  74,  34, 145, 133],
       [165,  75,  17, 194,  46,  14],
       [ 12, 158,  21, 198, 156, 146],
       [142, 138, 113, 111, 110,  50],
       [179,  31,  84, 137,  99,   2],
       [148,   7, 109,  97, 183, 191],
       [135,  79,  63, 104,  89, 121],
       [ 26,  41, 115, 111,  11,  28],
       [ 55, 154, 121, 158,  49, 109],
       [ 87,  10,  93,  72, 129, 186],
       [ 31, 101,  85, 191, 116,  91],
       [146, 154,  29, 181,  23,  68],
       [132,  25,  35, 146,  58,  44],
       [ 29,  83,  18,  18, 126, 100],
       [126,  71, 180,  22,  15,  62],
       [172,  13, 151,  82, 185,  90],
       [ 67, 106,  24, 162, 173, 119],
       [171, 189,  71,  36,  84, 123],
       [132,  73,  45,  35,  37,  94],
       [ 36, 171, 182,  39, 195,  90]])

In [36]:
f.shape

(25, 6)

In [37]:
f[1:5:2]

array([[ 77,  18,  61, 144, 159, 142],
       [ 34,  83, 142, 114,  13, 192]])

In [38]:
f[2,[3,4]]

array([147,  80])

In [39]:
f[[2,3,4],[2,3,4]]

array([  9, 114,  75])

In [40]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [41]:
np.exp(ar2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [42]:
np.sin(ar2)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [43]:
a2

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [44]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.log(ar2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [46]:
np.full((1,3),10)

array([[10, 10, 10]])

In [47]:
s=np.array([[1,2],[4,5],[7,8],[9,10]])
s

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10]])

In [48]:
s.flatten()

array([ 1,  2,  4,  5,  7,  8,  9, 10])

In [50]:
np.tile(s,2)

array([[ 1,  2,  1,  2],
       [ 4,  5,  4,  5],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

In [51]:
s

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10]])

In [52]:
np.resize(1,2)

array([1, 1])

In [53]:
import math

In [54]:
math.pi               #package.attribute

3.141592653589793

In [56]:
math.pow(2,3)         #package function

8.0